export type FAQ = {
  id: string;
  question: string;
  answer: string;
  category: "investment" | "legal" | "property" | "diaspora" | "general";
};

export const FAQS: FAQ[] = [
  {
    id: "f1",
    question: "What exactly is the 'Live or Earn' model?",
    answer:
      "Live or Earn is Engrite's signature flexibility clause. When you buy a property, you have two options: move in and live in it yourself (Live), or let Engrite's property management team lease it out to vetted tenants and remit rental income to you (Earn). You can switch between modes — for example, a diaspora buyer might Earn for 5 years, then switch to Live when they relocate back to Lagos. There is no fee for switching, and you retain full ownership throughout.",
    category: "investment",
  },
  {
    id: "f2",
    question: "What happens at the end of the 17-year lease?",
    answer:
      "The 17-year lease is a structural protection mechanism, not an expiration of ownership. You own the property outright — the lease refers to the structured investment and rental management framework. At year 17, you have three options: (1) renew the Live or Earn management agreement on updated terms, (2) take full self-management of the property, or (3) sell back to Engrite at a guaranteed minimum price based on a pre-agreed valuation formula. This exit optionality is built into every contract.",
    category: "investment",
  },
  {
    id: "f3",
    question: "Is my investment legally protected under Nigerian law?",
    answer:
      "Yes. Every Engrite property transaction is governed by a registered deed of assignment, notarized and registered with the Lagos State Lands Bureau. Your title is verifiable through a Certificate of Occupancy (C of O) or Governor's Consent, depending on the property. We work with Lagos-based real estate attorneys independent of Engrite to represent buyer interests during closing. The 5% legal fee you pay covers all of this — title verification, deed drafting, registration, and stamp duty.",
    category: "legal",
  },
  {
    id: "f4",
    question: "Can I buy property from outside Nigeria as a diaspora investor?",
    answer:
      "Absolutely — over 40% of our buyers are diaspora. The entire process is designed to be completed remotely: virtual tours (now with 360° walkthroughs), video calls with our sales team, electronic document signing, and international wire transfers in USD or GBP. We assign a dedicated diaspora concierge who handles your transaction end-to-end and provides weekly progress updates with photos and videos. Typical closing time for diaspora buyers is 21-30 days from initial inquiry.",
    category: "diaspora",
  },
  {
    id: "f5",
    question: "What are the payment plans for off-plan properties?",
    answer:
      "Off-plan properties (like Crest Residence) follow a milestone-based payment schedule tied to construction progress, not arbitrary dates. A typical schedule is: 10% reservation, 20% at foundation, 30% at superstructure, 25% at finishing, 15% at handover. This means you only pay as the building physically progresses — your capital is never sitting idle. The full schedule is documented in your purchase agreement before any payment is made.",
    category: "property",
  },
  {
    id: "f6",
    question: "What is the 5% legal fee and what does it cover?",
    answer:
      "The 5% legal fee is the only fee beyond the property purchase price. It is a one-time payment that covers: title verification at the Lands Bureau, deed of assignment drafting by an independent attorney, notarization, stamp duty, Lagos State land registry registration, and the structural warranty registration. There are no hidden marketing fees, agency fees, or management fees deducted at closing. Ongoing property management (if you choose Earn mode) is deducted from rental income, never billed separately.",
    category: "legal",
  },
  {
    id: "f7",
    question: "How is the 7.1% annual return calculated and paid?",
    answer:
      "The 7.1% return is calculated on your total purchase price and paid quarterly into your nominated bank account (Nigerian or international). It is derived from actual rental income generated by the property — Engrite's property management arm leases the unit, deducts a 15% management fee from rent collected, and remits the remainder to you. Returns are documented in quarterly statements showing rent collected, vacancy periods, maintenance costs, and net payout. You can audit any time.",
    category: "investment",
  },
  {
    id: "f8",
    question: "Can I visit the construction site before purchasing?",
    answer:
      "Yes, and we strongly encourage it for local buyers. Site visits can be booked through our booking widget — typically a 90-minute guided tour with a sales consultant who walks you through the unit mix, construction quality, and neighborhood. For off-plan properties where construction hasn't begun, we'll show you comparable completed projects (Sinai Spaces or Sinai Residence) so you can evaluate Engrite's build quality firsthand. Diaspora buyers can book virtual site tours via video call.",
    category: "property",
  },
  {
    id: "f9",
    question: "What happens if construction is delayed?",
    answer:
      "Every Engrite purchase agreement includes a liquidated damages clause: if handover is delayed beyond the committed date by more than 60 days due to Engrite's fault (not force majeure), you receive a daily penalty credit applied to your final payment. We have never invoked force majeure. Our track record: Sinai Spaces delivered on original committed date, Sinai Residence delivered 3 weeks early. We publish monthly progress updates with photos so buyers can verify construction status independently.",
    category: "legal",
  },
  {
    id: "f10",
    question: "Can I sell my property before the 17-year lease ends?",
    answer:
      "Yes — you can sell at any time. The lease structure does not restrict resale. Engrite offers a 'reselling assurance' program: if you choose to sell, we will list the property through our buyer network first (typically achieving 8-12% above market due to our pre-vetted buyer pool). If you prefer to sell independently, you're free to do so with any realtor. The deed of assignment transfer process takes 14-21 days.",
    category: "investment",
  },
  {
    id: "f11",
    question: "Are there any restrictions on foreign (non-Nigerian) buyers?",
    answer:
      "Foreign nationals can buy property in Lagos subject to the same process as Nigerian citizens, with one additional step: obtaining a Minister's Consent for land transfer (we handle this as part of the 5% legal fee package). Foreign buyers are eligible for the same Live or Earn model, the same 17-year lease structure, and the same 7.1% return. Rental income is subject to 10% withholding tax, which we deduct and remit on your behalf.",
    category: "diaspora",
  },
  {
    id: "f12",
    question: "How do I get started if I'm interested?",
    answer:
      "Three ways: (1) Fill out the contact form on this page and tell us your budget and interest area — we'll respond within 24 hours with a tailored shortlist. (2) Book a site visit through the booking widget to see properties in person. (3) Chat with us on WhatsApp at +234 813 066 5862 for immediate questions. There is no obligation at any stage of the conversation — we'd rather you make an informed decision than a pressured one.",
    category: "general",
  },
];
